### ISSUE TITLE
Allow multiple devices

### ISSUE THREAD

**Issue by zpeters** [zpeters/nerdnest#1]

**Comment by tturner** [comment]
Any ideas on how you'd want this implemented?
My thoughts:

- Update the configuration format to allow a new key called devicelist, make this a list of device ids.
- Allow commands to optionally have a device number parameter. Default to the first device in list if no device number provided.

Happy to implement this if we can agree how it should be done - if you had a different idea in mind let me know.

**Comment by zpeters** [comment]
I think this sounds great.  Truthfully, i haven't given it a lot of thought but the approach here makes sense.  I like defaulting to a "primary" device if no parameter is specified.  Sounds like a plan to me!

**Comment by tturner** [comment]
Ok, I've implemented this in my fork. It has some dependencies on the other changes I've made in my other pull requests so I can't easily create a clean pull request yet, until you have accepted those requests.

You can have a play with all the features I have implemented if you clone my repo though :-)

**Comment by zpeters** [comment]
Merged the existing pull requests.  Happy to pull in the rest of your
work.  This is great stuff!

**Comment by tturner** [comment]
I'm glad you like it - I'm very new to golang so I suspect my code isn't great Go :). I really like this project because it works so well and is simple and clear. Other go nest stuff looks more complex or out of date. Thanks for creating this.

I've just made it support saving a log file for long term stats generation. Now I just need to decide how best to chart the data :)

**Comment by zpeters** [comment]
Merged pull requests.  Thanks @tturner
